apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: john-new-app
  description: john-new-app
  annotations:
    github.com/project-slug: excessivedemon/john-new-app
    backstage.io/techdocs-ref: dir:./docs 
    backstage.io/api-docs: john-new-app-api
spec:
  type: service
  lifecycle: experimental
  owner: guest
  providesApis:
    - default/john-new-app-api

---

# API entity
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: john-new-app-api
  description: API for john-new-app
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition: |
    openapi: 3.0.0
    info:
      title: john-new-app API
      version: 1.0.0
    paths:
      /:
        get:
          summary: Health check endpoint
          responses:
            '200':
              description: Successful response
